### ISSUE TITLE
pmcmds.py does not exist or its not unique

### ISSUE THREAD

**Issue by monsreal** [AutodeskRoboticsLab/Mimic#1]
Hi,
I installed Mimic in Maya 2017, and I am having this error when trying to save a program:
![image](https://user-images.githubusercontent.com/42876931/46180757-fd83c180-c276-11e8-8469-f869fa0eb0cb.png)
 any suggestions?

Thank you

**Comment by evanatherton** [comment]
Ah, there was a small typo on that attribute on that particular rig. I had fixed it but looks like I must've pulled on old version. 

I'll fix it first thing in the morning and republish. Sorry about that

**Comment by monsreal** [comment]
Great! Thank you.
Iván

**Comment by evanatherton** [comment]
Just uploaded the new version to the latest release!
