### ISSUE TITLE
Analyse Program fails to load graph representation; warning that numpy should be installed correctly

### ISSUE THREAD

**Issue by bootsch** [AutodeskRoboticsLab/Mimic#3]
On MacOS 10.13/10.14 - Maya 2018.

Numpy is installed by default and can be imported from the maya python commandline

`import numpy`
`# Warning: MIMIC: Analysis module did not load successfully; analysis graphing feature disabled. Check that you have numPy installed properly; see Mimic installation instructions for more details`
`import numpy`

**Comment by bootsch** [comment]
It seems the error is in Qt.py importing QtGui

`import pyqtgraph`
`# Error: ImportError: file /Users/username/Library/Preferences/Autodesk/maya/modules/mimic/scripts/extern/pyqtgraph/Qt.py line 154: cannot import name QtGui`

**Comment by bootsch** [comment]
Thru the grapevine I hear: "Appears the easiest way to 'fix' this issue for us was to reorder the Qt import list:  In scripts/extern/pyqtgraph/Qt.py:  libOrder = [PYSIDE2, PYQT5, PYSIDE, PYQT4]"
Yet to test this, just to put the note down.

**Comment by bootsch** [comment]
Thru the grapevine I hear: "Appears the easiest way to 'fix' this issue for us was to reorder the Qt import list:  In scripts/extern/pyqtgraph/Qt.py:  libOrder = [PYSIDE2, PYQT5, PYSIDE, PYQT4]"
Yet to test this, just to put the note down.

**Comment by bootsch** [comment]
It works.
Change the current line
https://github.com/AutodeskRoboticsLab/Mimic/blob/15155b97074a26f30b5a9218ed5739ccfb5638fb/mimic/scripts/extern/pyqtgraph/Qt.py#L28
to 
`libOrder = [PYSIDE2, PYQT5, PYSIDE, PYQT4]`

**Comment by bootsch** [comment]
The solution came from Mimic users on Linux.

**Comment by evanatherton** [comment]
Pushed this fix to the master branch
