### ISSUE TITLE
Where can find KUKA KR 120 R3500 press C model for Mimic

### ISSUE THREAD

**Issue by d4nielbaez** [AutodeskRoboticsLab/Mimic#30]
Hi, where can i find the KUKA KR 120 R3500 press C model??

**Comment by evanatherton** [comment]
Hey @d4nielbaez, sorry for the delay on this, here's the [KUKA KR 120 R3500 press C](https://www.dropbox.com/s/czpwvc8ho5cp1sy/KR%20120%20R3500%20press%20C.ma?dl=0)

Just download that and add it to the mimic/rigs/KUKA folder and it'll automatically show up in the robot dropdown list in the Mimic UI
