### ISSUE TITLE
Sample Rate in mPrefs is set as Int while it's a Float in main UI

### ISSUE THREAD

**Issue by aatb-ch** [AutodeskRoboticsLab/Mimic#34]
The Sample Rate setting is normally a Float input, so that when picking a sample rate in Seconds you set the interval with second units. It's currently an Int field in mPrefs which prevents to use custom intervals to sample at certain specific robot controller frequencies (eg 125Hz = 0.008s, 500Hz = 0.002s)

https://github.com/AutodeskRoboticsLab/Mimic/blob/7287c65a8b0d95f8b2212a1214c8cb28f0644430/mimic/scripts/mimic_prefs_ui.py#L356

https://github.com/AutodeskRoboticsLab/Mimic/blob/7287c65a8b0d95f8b2212a1214c8cb28f0644430/mimic/scripts/mimic_ui.py#L507

**Comment by evanatherton** [comment]
hmmm...I [thought](https://github.com/AutodeskRoboticsLab/Mimic/pull/22#issuecomment-747748063) I fixed that. I must've only fixed the one in the main UI but not the prefs

Thanks for catching that - Will take a look!

**Comment by evanatherton** [comment]
Fixed :)

57e7119c7d6960181443eecd858d2554ed4fe7e8
