### ISSUE TITLE
Column Name not included when exporting External Axises in General CSV Export

### ISSUE THREAD

**Issue by aatb-ch** [AutodeskRoboticsLab/Mimic#35]
When exporting External Axises with the General CSV Export, one would expect to have the Axis Name as title of the column. Currently it exports correctly each rows but the titles are left empty, which makes it impossible to parse safely.

Current:

```
Time, Axis 1, Axis 2, Axis 3, Axis 4, Axis 5, Axis 6
0.000000, 34.014935, -68.899895, 81.252899, 167.647003, -34.014935, 0.000000, 0.000000
```

Expected:

```
Time, Axis 1, Axis 2, Axis 3, Axis 4, Axis 5, Axis 6, Axis 7
0.000000, 34.014935, -68.899895, 81.252899, 167.647003, -34.014935, 0.000000, 0.000000
```

**Comment by evanatherton** [comment]
The column name is actually determined by the CSV template file, [template.CSV](https://github.com/AutodeskRoboticsLab/Mimic/blob/master/mimic/scripts/postproc/GENERAL/CSV/template.csv), that's found in `mimic/scripts/postproc/GENERAL/CSV`

So just edit that, or create a new template for different setups if you prefer, then all exported programs will have your edited header
