### ISSUE TITLE
Sample rate in Mimic Preferences should be float

### ISSUE THREAD

**Issue by Brucepimenta** [AutodeskRoboticsLab/Mimic#40]
The "Sample rate" field is defined as integer, but should be float.

mimic_prefs_ui.py:356
```
 pm.intField(minValue=0,
```

expected:
```
 pm.floatField(minValue=0,
```

**Comment by aatb-ch** [comment]
Are you running the release version? it's already fixed in Master, if you directly pull the repo

https://github.com/AutodeskRoboticsLab/Mimic/blob/85447f0d346be66988303a6a054473d92f1ed6f4/mimic/scripts/mimic_prefs_ui.py#L356

**Comment by aatb-ch** [comment]
duplicate of https://github.com/AutodeskRoboticsLab/Mimic/issues/34

**Comment by Brucepimenta** [comment]
You are right, I was using the release version. I didn't check the Master, it is fixed there, thanks!
