### ISSUE TITLE
Does mimic work with maya 2023?

### ISSUE THREAD

**Issue by sergiosolorzano** [AutodeskRoboticsLab/Mimic#41]
I tried [downgrading to python 2](https://github.com/AutodeskRoboticsLab/Mimic/issues/37) but doesn't let me. 

I see [Maya no longer supports Python2, and can no longer be started in Python 2 mode.](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2023/ENU/Maya-WhatsNewPR/files/GUID-DF43840B-4DB1-43F8-BFD1-97D8D031B91D-htm.html)

Does mimic work with maya 2023?

**Comment by evanatherton** [comment]
Hi @sergiosolorzano - apologies for that. I still haven't published the Python 3 version as a release. Please try downloading one of these directly depending on your operating system and let me know if you run into any trouble

[Mimic for Maya 2023 - MAC](https://www.dropbox.com/s/scp86999mfi45qr/mimic3-1.5.0_MAC.zip?dl=0)
[Mimic for Maya 2023 - WIN](https://www.dropbox.com/s/e52ibn6wtrecyfq/mimic3-1.5.0_WIN.zip?dl=0)
