### ISSUE TITLE
Control KUKA in real-time

### ISSUE THREAD

**Issue by abbott1234** [AutodeskRoboticsLab/Mimic#7]

**Comment by abbott1234** [comment]
how can I use Mimic to control the kuka robot in real-time

**Comment by evanatherton** [comment]
Currently Mimic doesn't support realtime communication; however, there are a few users in the Mimic community that are working on that now so I'm hoping there will be a solution available soon.

Feel free to join the Slack group if you'd like to connect with the community on it:
You can sign up here
https://www.mimicformaya.com/#community-section

**Comment by abbott1234** [comment]
> Currently Mimic doesn't support realtime communication; however, there are a few users in the Mimic community that are working on that now so I'm hoping there will be a solution available soon.
> 
> Feel free to join the Slack group if you'd like to connect with the community on it:
> You can sign up here
> https://www.mimicformaya.com/#community-section

Yeap, I have joined it, but strange there. Do you have some material for realtime communication?
